<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;
use App\Models\Continent;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            'Africa' => [
                'Algeria' => ['code' => 'DZD', 'sign' => 'د.ج', 'nationality' => 'Algerian', 'country_code' => 'DZ', 'stripe_supported_country_type' => null , 'stripe_supported_country_type' => null],
                'Angola' => ['code' => 'AOA', 'sign' => 'Kz', 'nationality' => 'Angolan'  , 'country_code' => 'AO' , 'stripe_supported_country_type' => null],
                'Benin' => ['code' => 'XOF', 'sign' => 'CFA', 'nationality' => 'Beninese'  , 'country_code' => 'BJ' , 'stripe_supported_country_type' => null],
                'Botswana' => ['code' => 'BWP', 'sign' => 'P', 'nationality' => 'Botswanan'  , 'country_code' => 'BW' , 'stripe_supported_country_type' => null],
                'Burkina Faso' => ['code' => 'XOF', 'sign' => 'CFA', 'nationality' => 'Burkinabe'  , 'country_code' => 'BF' , 'stripe_supported_country_type' => null],
                'Burundi' => ['code' => 'BIF', 'sign' => 'FBu', 'nationality' => 'Burundian'  , 'country_code' => 'BI' , 'stripe_supported_country_type' => null],
                'Cape Verde' => ['code' => 'CVE', 'sign' => 'Esc', 'nationality' => 'Cape Verdean'  , 'country_code' => 'CV' , 'stripe_supported_country_type' => null],
                'Cameroon' => ['code' => 'XAF', 'sign' => 'FCFA', 'nationality' => 'Cameroonian'  , 'country_code' => 'CD' , 'stripe_supported_country_type' => null],
                'Central African Republic' => ['code' => 'XAF', 'sign' => 'FCFA', 'nationality' => 'Central African'  , 'country_code' => 'CF' , 'stripe_supported_country_type' => null],
                'Chad' => ['code' => 'XAF', 'sign' => 'FCFA', 'nationality' => 'Chadian'  , 'country_code' => 'TD' , 'stripe_supported_country_type' => null],
                'Comoros' => ['code' => 'KMF', 'sign' => 'CF', 'nationality' => 'Comorian'  , 'country_code' => 'KM' , 'stripe_supported_country_type' => null],
                'Democratic Republic of the Congo' => ['code' => 'CDF', 'sign' => 'FC', 'nationality' => 'Congolese (Democratic Republic)'  , 'country_code' => 'CD' , 'stripe_supported_country_type' => null],
                'Republic of the Congo' => ['code' => 'XAF', 'sign' => 'FCFA', 'nationality' => 'Congolese (Republic)'  , 'country_code' => 'ZR' , 'stripe_supported_country_type' => null],
                'Djibouti' => ['code' => 'DJF', 'sign' => 'Fdj', 'nationality' => 'Djiboutian'  , 'country_code' => 'DJ' , 'stripe_supported_country_type' => null],
                'Egypt' => ['code' => 'EGP', 'sign' => 'E£', 'nationality' => 'Egyptian'  , 'country_code' => 'EG' , 'stripe_supported_country_type' => null],
                'Equatorial Guinea' => ['code' => 'XAF', 'sign' => 'FCFA', 'nationality' => 'Equatorial Guinean' , 'country_code' => 'GQ' , 'stripe_supported_country_type' => null],
                'Eritrea' => ['code' => 'ERN', 'sign' => 'Nfk', 'nationality' => 'Eritrean' , 'country_code' => 'ER' , 'stripe_supported_country_type' => null],
                'Eswatini' => ['code' => 'SZL', 'sign' => 'E', 'nationality' => 'Swazi' , 'country_code' => 'SZ' , 'stripe_supported_country_type' => null],
                'Ethiopia' => ['code' => 'ETB', 'sign' => 'Br', 'nationality' => 'Ethiopian' , 'country_code' => 'ET' , 'stripe_supported_country_type' => null],
                'Gabon' => ['code' => 'XAF', 'sign' => 'FCFA', 'nationality' => 'Gabonese' , 'country_code' => 'GA' , 'stripe_supported_country_type' => null],
                'Gambia' => ['code' => 'GMD', 'sign' => 'D', 'nationality' => 'Gambian' , 'country_code' => 'GM' , 'stripe_supported_country_type' => null],
                'Ghana' => ['code' => 'GHS', 'sign' => '₵', 'nationality' => 'Ghanaian' , 'country_code' => 'GH' , 'stripe_supported_country_type' => 'GH'],
                'Guinea' => ['code' => 'GNF', 'sign' => 'FG', 'nationality' => 'Guinean' , 'country_code' => 'GN' , 'stripe_supported_country_type' => null],
                'Guinea-Bissau' => ['code' => 'XOF', 'sign' => 'CFA', 'nationality' => 'Bissau-Guinean' , 'country_code' => 'GW' , 'stripe_supported_country_type' => null],
                'Ivory Coast' => ['code' => 'XOF', 'sign' => 'CFA', 'nationality' => 'Ivorian' , 'country_code' => 'CI' , 'stripe_supported_country_type' => null],
                'Kenya' => ['code' => 'KES', 'sign' => 'KSh', 'nationality' => 'Kenyan' , 'country_code' => 'KE' , 'stripe_supported_country_type' => 'KE'],
                'Lesotho' => ['code' => 'LSL', 'sign' => 'L', 'nationality' => 'Basotho'  , 'country_code' => 'LS' , 'stripe_supported_country_type' => null],
                'Liberia' => ['code' => 'LRD', 'sign' => 'L$', 'nationality' => 'Liberian'  , 'country_code' => 'LR' , 'stripe_supported_country_type' => null],
                'Libya' => ['code' => 'LYD', 'sign' => 'LD', 'nationality' => 'Libyan'  , 'country_code' => 'LY' , 'stripe_supported_country_type' => null],
                'Madagascar' => ['code' => 'MGA', 'sign' => 'Ar', 'nationality' => 'Malagasy', 'country_code' => 'MG' , 'stripe_supported_country_type' => null],
                'Malawi' => ['code' => 'MWK', 'sign' => 'MK', 'nationality' => 'Malawian', 'country_code' => 'MW' , 'stripe_supported_country_type' => null],
                'Mali' => ['code' => 'XOF', 'sign' => 'CFA', 'nationality' => 'Malian', 'country_code' => 'ML' , 'stripe_supported_country_type' => null],
                'Mauritania' => ['code' => 'MRU', 'sign' => 'UM', 'nationality' => 'Mauritanian', 'country_code' => 'MR' , 'stripe_supported_country_type' => null],
                'Mauritius' => ['code' => 'MUR', 'sign' => 'Rs', 'nationality' => 'Mauritian', 'country_code' => 'MU' , 'stripe_supported_country_type' => null],
                'Morocco' => ['code' => 'MAD', 'sign' => 'DH', 'nationality' => 'Moroccan', 'country_code' => 'MA' , 'stripe_supported_country_type' => null],
                'Mozambique' => ['code' => 'MZN', 'sign' => 'MT', 'nationality' => 'Mozambican', 'country_code' => 'MZ' , 'stripe_supported_country_type' => null],
                'Namibia' => ['code' => 'NAD', 'sign' => 'N$', 'nationality' => 'Namibian', 'country_code' => 'NA' , 'stripe_supported_country_type' => null],
                'Niger' => ['code' => 'XOF', 'sign' => 'CFA', 'nationality' => 'Nigerien', 'country_code' => 'NE' , 'stripe_supported_country_type' => null],
                'Nigeria' => ['code' => 'NGN', 'sign' => '₦', 'nationality' => 'Nigerian', 'country_code' => 'NG' , 'stripe_supported_country_type' => 'NG'],
                'Rwanda' => ['code' => 'RWF', 'sign' => 'RF', 'nationality' => 'Rwandan', 'country_code' => 'RW' , 'stripe_supported_country_type' => null],
                'São Tomé and Príncipe' => ['code' => 'STN', 'sign' => 'Db', 'nationality' => 'São Toméan', 'country_code' => 'ST' , 'stripe_supported_country_type' => null],
                'Senegal' => ['code' => 'XOF', 'sign' => 'CFA', 'nationality' => 'Senegalese', 'country_code' => 'SN' , 'stripe_supported_country_type' => null],
                'Seychelles' => ['code' => 'SCR', 'sign' => 'SR', 'nationality' => 'Seychellois', 'country_code' => 'SC' , 'stripe_supported_country_type' => null],
                'Sierra Leone' => ['code' => 'SLL', 'sign' => 'Le', 'nationality' => 'Sierra Leonean', 'country_code' => 'SL' , 'stripe_supported_country_type' => null],
                'Somalia' => ['code' => 'SOS', 'sign' => 'Sh.So.', 'nationality' => 'Somali', 'country_code' => 'SO' , 'stripe_supported_country_type' => null],
                'South Africa' => ['code' => 'ZAR', 'sign' => 'R', 'nationality' => 'South African', 'country_code' => 'ZA' , 'stripe_supported_country_type' => 'ZA'],
                'South Sudan' => ['code' => 'SSP', 'sign' => '£', 'nationality' => 'South Sudanese', 'country_code' => 'SS' , 'stripe_supported_country_type' => null],
                'Sudan' => ['code' => 'SDG', 'sign' => 'SDG', 'nationality' => 'Sudanese', 'country_code' => 'SD' , 'stripe_supported_country_type' => null],
                'Tanzania' => ['code' => 'TZS', 'sign' => 'TSh', 'nationality' => 'Tanzanian', 'country_code' => 'TZ' , 'stripe_supported_country_type' => null],
                'Togo' => ['code' => 'XOF', 'sign' => 'CFA', 'nationality' => 'Togolese', 'country_code' => 'TG' , 'stripe_supported_country_type' => null],
                'Tunisia' => ['code' => 'TND', 'sign' => 'DT', 'nationality' => 'Tunisian', 'country_code' => 'TN' , 'stripe_supported_country_type' => null],
                'Uganda' => ['code' => 'UGX', 'sign' => 'USh', 'nationality' => 'Ugandan', 'country_code' => 'UG' , 'stripe_supported_country_type' => null],
                'Zambia' => ['code' => 'ZMW', 'sign' => 'ZK', 'nationality' => 'Zambian', 'country_code' => 'ZM' , 'stripe_supported_country_type' => null],
                'Zimbabwe' => ['code' => 'ZWL', 'sign' => 'Z$', 'nationality' => 'Zimbabwean', 'country_code' => 'ZW' , 'stripe_supported_country_type' => null]
            ],
            'Asia' => [
                'Afghanistan' => ['code' => 'AFN', 'sign' => '؋', 'nationality' => 'Afghan', 'country_code' => 'AF' , 'stripe_supported_country_type' => null],
                'Armenia' => ['code' => 'AMD', 'sign' => '֏', 'nationality' => 'Armenian', 'country_code' => 'AM' , 'stripe_supported_country_type' => null],
                'Azerbaijan' => ['code' => 'AZN', 'sign' => '₼', 'nationality' => 'Azerbaijani', 'country_code' => 'AZ' , 'stripe_supported_country_type' => null],
                'Bahrain' => ['code' => 'BHD', 'sign' => 'BD', 'nationality' => 'Bahraini', 'country_code' => 'BH' , 'stripe_supported_country_type' => null],
                'Bangladesh' => ['code' => 'BDT', 'sign' => '৳', 'nationality' => 'Bangladeshi', 'country_code' => 'BD' , 'stripe_supported_country_type' => null],
                'Bhutan' => ['code' => 'BTN', 'sign' => 'Nu.', 'nationality' => 'Bhutanese', 'country_code' => 'BT' , 'stripe_supported_country_type' => null],
                'Brunei' => ['code' => 'BND', 'sign' => 'B$', 'nationality' => 'Bruneian', 'country_code' => 'BN' , 'stripe_supported_country_type' => null],
                'Cambodia' => ['code' => 'KHR', 'sign' => '៛', 'nationality' => 'Cambodian', 'country_code' => 'KH' , 'stripe_supported_country_type' => null],
                'China' => ['code' => 'CNY', 'sign' => '¥', 'nationality' => 'Chinese', 'country_code' => 'CN' , 'stripe_supported_country_type' => null],
                'Cyprus' => ['code' => 'EUR', 'sign' => '€', 'nationality' => 'Cypriot', 'country_code' => 'CY' , 'stripe_supported_country_type' => null],
                'Georgia' => ['code' => 'GEL', 'sign' => '₾', 'nationality' => 'Georgian', 'country_code' => 'GE' , 'stripe_supported_country_type' => null],
                'India' => ['code' => 'INR', 'sign' => '₹', 'nationality' => 'Indian', 'country_code' => 'IN' , 'stripe_supported_country_type' => 'IN'],
                'Indonesia' => ['code' => 'IDR', 'sign' => 'Rp', 'nationality' => 'Indonesian', 'country_code' => 'ID' , 'stripe_supported_country_type' => 'ID'],
                'Iran' => ['code' => 'IRR', 'sign' => '﷼', 'nationality' => 'Iranian', 'country_code' => 'IR' , 'stripe_supported_country_type' => null],
                'Iraq' => ['code' => 'IQD', 'sign' => 'د.ع', 'nationality' => 'Iraqi', 'country_code' => 'IQ' , 'stripe_supported_country_type' => null],
                'Israel' => ['code' => 'ILS', 'sign' => '₪', 'nationality' => 'Israeli', 'country_code' => 'IL' , 'stripe_supported_country_type' => null],
                'Japan' => ['code' => 'JPY', 'sign' => '¥', 'nationality' => 'Japanese', 'country_code' => 'JP' , 'stripe_supported_country_type' => 'JP'],
                'Jordan' => ['code' => 'JOD', 'sign' => 'JD', 'nationality' => 'Jordanian', 'country_code' => 'JO' , 'stripe_supported_country_type' => null],
                'Kazakhstan' => ['code' => 'KZT', 'sign' => '₸', 'nationality' => 'Kazakh', 'country_code' => 'KZ' , 'stripe_supported_country_type' => null],
                'Kuwait' => ['code' => 'KWD', 'sign' => 'KD', 'nationality' => 'Kuwaiti', 'country_code' => 'KW' , 'stripe_supported_country_type' => null],
                'Kyrgyzstan' => ['code' => 'KGS', 'sign' => 'сом', 'nationality' => 'Kyrgyz', 'country_code' => 'KG' , 'stripe_supported_country_type' => null],
                'Laos' => ['code' => 'LAK', 'sign' => '₭', 'nationality' => 'Lao', 'country_code' => 'LA' , 'stripe_supported_country_type' => null],
                'Lebanon' => ['code' => 'LBP', 'sign' => 'ل.ل', 'nationality' => 'Lebanese', 'country_code' => 'LB' , 'stripe_supported_country_type' => null],
                'Malaysia' => ['code' => 'MYR', 'sign' => 'RM', 'nationality' => 'Malaysian', 'country_code' => 'MY' , 'stripe_supported_country_type' => 'MY'],
                'Maldives' => ['code' => 'MVR', 'sign' => 'ރ', 'nationality' => 'Maldivian', 'country_code' => 'MV' , 'stripe_supported_country_type' => null],
                'Mongolia' => ['code' => 'MNT', 'sign' => '₮', 'nationality' => 'Mongolian', 'country_code' => 'MN' , 'stripe_supported_country_type' => null],
                'Myanmar (Burma)' => ['code' => 'MMK', 'sign' => 'Ks', 'nationality' => 'Burmese', 'country_code' => 'MM' , 'stripe_supported_country_type' => null],
                'Nepal' => ['code' => 'NPR', 'sign' => '₨', 'nationality' => 'Nepali', 'country_code' => 'NP' , 'stripe_supported_country_type' => null],
                'North Korea' => ['code' => 'KPW', 'sign' => '₩', 'nationality' => 'North Korean', 'country_code' => 'KP' , 'stripe_supported_country_type' => null],
                'Oman' => ['code' => 'OMR', 'sign' => 'ر.ع.', 'nationality' => 'Omani', 'country_code' => 'OM' , 'stripe_supported_country_type' => null],
                'Pakistan' => ['code' => 'PKR', 'sign' => '₨', 'nationality' => 'Pakistani', 'country_code' => 'PK' , 'stripe_supported_country_type' => null],
                'Palestine' => ['code' => 'ILS', 'sign' => '₪', 'nationality' => 'Palestinian', 'country_code' => 'PS' , 'stripe_supported_country_type' => null],
                'Philippines' => ['code' => 'PHP', 'sign' => '₱', 'nationality' => 'Filipino', 'country_code' => 'PH' , 'stripe_supported_country_type' => null],
                'Qatar' => ['code' => 'QAR', 'sign' => 'ر.ق', 'nationality' => 'Qatari', 'country_code' => 'QA' , 'stripe_supported_country_type' => null],
                'Russia' => ['code' => 'RUB', 'sign' => '₽', 'nationality' => 'Russian', 'country_code' => 'RU' , 'stripe_supported_country_type' => null],
                'Saudi Arabia' => ['code' => 'SAR', 'sign' => 'ر.س', 'nationality' => 'Saudi', 'country_code' => 'SA' , 'stripe_supported_country_type' => null],
                'Singapore' => ['code' => 'SGD', 'sign' => 'S$', 'nationality' => 'Singaporean', 'country_code' => 'SG' , 'stripe_supported_country_type' => 'SG'],
                'South Korea' => ['code' => 'KRW', 'sign' => '₩', 'nationality' => 'South Korean', 'country_code' => 'KR' , 'stripe_supported_country_type' => null],
                'Sri Lanka' => ['code' => 'LKR', 'sign' => 'රු', 'nationality' => 'Sri Lankan', 'country_code' => 'LK' , 'stripe_supported_country_type' => null],
                'Syria' => ['code' => 'SYP', 'sign' => '£', 'nationality' => 'Syrian', 'country_code' => 'SY' , 'stripe_supported_country_type' => null],
                'Taiwan' => ['code' => 'TWD', 'sign' => 'NT$', 'nationality' => 'Taiwanese', 'country_code' => 'TW' , 'stripe_supported_country_type' => null],
                'Tajikistan' => ['code' => 'TJS', 'sign' => 'сом', 'nationality' => 'Tajik', 'country_code' => 'TJ' , 'stripe_supported_country_type' => null],
                'Thailand' => ['code' => 'THB', 'sign' => '฿', 'nationality' => 'Thai', 'country_code' => 'TH' , 'stripe_supported_country_type' => 'TH'],
                'Timor-Leste' => ['code' => 'USD', 'sign' => '$', 'nationality' => 'Timorese', 'country_code' => 'TL' , 'stripe_supported_country_type' => null],
                'Turkey' => ['code' => 'TRY', 'sign' => '₺', 'nationality' => 'Turkish', 'country_code' => 'TR' , 'stripe_supported_country_type' => null],
                'Turkmenistan' => ['code' => 'TMT', 'sign' => 'm', 'nationality' => 'Turkmen', 'country_code' => 'TM' , 'stripe_supported_country_type' => null],
                'United Arab Emirates' => ['code' => 'AED', 'sign' => 'د.إ', 'nationality' => 'Emirati', 'country_code' => 'AE' , 'stripe_supported_country_type' => 'AE'],
                'Uzbekistan' => ['code' => 'UZS', 'sign' => 'сум', 'nationality' => 'Uzbek', 'country_code' => 'UZ' , 'stripe_supported_country_type' => null],
                'Vietnam' => ['code' => 'VND', 'sign' => '₫', 'nationality' => 'Vietnamese', 'country_code' => 'VN' , 'stripe_supported_country_type' => null],
                'Yemen' => ['code' => 'YER', 'sign' => '﷼', 'nationality' => 'Yemeni', 'country_code' => 'YE' , 'stripe_supported_country_type' => null],
            ],

            'Europe' => [
                'Albania' => ['code' => 'ALL', 'sign' => 'Lek', 'nationality' => 'Albanian', 'country_code' => 'AL' , 'stripe_supported_country_type' => null],
                'Andorra' => ['code' => 'EUR', 'sign' => '€', 'nationality' => 'Andorran', 'country_code' => 'AD' , 'stripe_supported_country_type' => null],
                'Armenia' => ['code' => 'AMD', 'sign' => '֏', 'nationality' => 'Armenian', 'country_code' => 'AM' , 'stripe_supported_country_type' => null],
                'Austria' => ['code' => 'EUR', 'sign' => '€', 'nationality' => 'Austrian', 'country_code' => 'AT', 'stripe_supported_country_type' => 'AT'],
                'Azerbaijan' => ['code' => 'AZN', 'sign' => '₼', 'nationality' => 'Azerbaijani', 'country_code' => 'AZ' , 'stripe_supported_country_type' => null],
                'Belarus' => ['code' => 'BYN', 'sign' => 'Br', 'nationality' => 'Belarusian', 'country_code' => 'BY' , 'stripe_supported_country_type' => null],
                'Belgium' => ['code' => 'EUR', 'sign' => '€', 'nationality' => 'Belgian', 'country_code' => 'BE' , 'stripe_supported_country_type' => 'BE'],
                'Bosnia and Herzegovina' => ['code' => 'BAM', 'sign' => 'KM', 'nationality' => 'Bosnian', 'country_code' => 'BA', 'stripe_supported_country_type' => 'BA'],
                'Bulgaria' => ['code' => 'BGN', 'sign' => 'лв', 'nationality' => 'Bulgarian', 'country_code' => 'BG' , 'stripe_supported_country_type' => null],
                'Croatia' => ['code' => 'HRK', 'sign' => 'kn', 'nationality' => 'Croatian', 'country_code' => 'HR',  'stripe_supported_country_type' => 'HR'],
                'Cyprus' => ['code' => 'EUR', 'sign' => '€', 'nationality' => 'Cypriot', 'country_code' => 'CY' , 'stripe_supported_country_type' => 'CY'],
                'Czech Republic' => ['code' => 'CZK', 'sign' => 'Kč', 'nationality' => 'Czech', 'country_code' => 'CZ' , 'stripe_supported_country_type' => 'CZ'],
                'Denmark' => ['code' => 'DKK', 'sign' => 'kr', 'nationality' => 'Danish', 'country_code' => 'DK' , 'stripe_supported_country_type' => 'DK'],
                'Estonia' => ['code' => 'EUR', 'sign' => '€', 'nationality' => 'Estonian', 'country_code' => 'EE' , 'stripe_supported_country_type' => 'EE'],
                'Finland' => ['code' => 'EUR', 'sign' => '€', 'nationality' => 'Finnish', 'country_code' => 'FI' , 'stripe_supported_country_type' => 'FI'],
                'France' => ['code' => 'EUR', 'sign' => '€', 'nationality' => 'French', 'country_code' => 'FR' , 'stripe_supported_country_type' => 'FR'],
                'Georgia' => ['code' => 'GEL', 'sign' => '₾', 'nationality' => 'Georgian', 'country_code' => 'GE' , 'stripe_supported_country_type' => null],
                'Germany' => ['code' => 'EUR', 'sign' => '€', 'nationality' => 'German', 'country_code' => 'DE' , 'stripe_supported_country_type' => 'DE'],
                'Greece' => ['code' => 'EUR', 'sign' => '€', 'nationality' => 'Greek', 'country_code' => 'GR' , 'stripe_supported_country_type' => 'GR'],
                'Hungary' => ['code' => 'HUF', 'sign' => 'Ft', 'nationality' => 'Hungarian', 'country_code' => 'HU' , 'stripe_supported_country_type' => 'HU'],
                'Iceland' => ['code' => 'ISK', 'sign' => 'kr', 'nationality' => 'Icelandic', 'country_code' => 'IS' , 'stripe_supported_country_type' => null],
                'Ireland' => ['code' => 'EUR', 'sign' => '€', 'nationality' => 'Irish', 'country_code' => 'IE' , 'stripe_supported_country_type' => 'IE'],
                'Italy' => ['code' => 'EUR', 'sign' => '€', 'nationality' => 'Italian', 'country_code' => 'IT' , 'stripe_supported_country_type' => 'IT'],
                'Kazakhstan' => ['code' => 'KZT', 'sign' => '₸', 'nationality' => 'Kazakhstani', 'country_code' => 'KZ' , 'stripe_supported_country_type' => null],
                'Kosovo' => ['code' => 'EUR', 'sign' => '€', 'nationality' => 'Kosovar', 'country_code' => 'XK' , 'stripe_supported_country_type' => null],
                'Latvia' => ['code' => 'EUR', 'sign' => '€', 'nationality' => 'Latvian', 'country_code' => 'LV' , 'stripe_supported_country_type' => 'LV'],
                'Liechtenstein' => ['code' => 'CHF', 'sign' => 'Fr', 'nationality' => 'Liechtensteiner', 'country_code' => 'LI' , 'stripe_supported_country_type' => 'LI'],
                'Lithuania' => ['code' => 'EUR', 'sign' => '€', 'nationality' => 'Lithuanian', 'country_code' => 'LT' , 'stripe_supported_country_type' => 'LT'],
                'Luxembourg' => ['code' => 'EUR', 'sign' => '€', 'nationality' => 'Luxembourgish', 'country_code' => 'LU' , 'stripe_supported_country_type' => 'LU'],
                'Malta' => ['code' => 'EUR', 'sign' => '€', 'nationality' => 'Maltese', 'country_code' => 'MT' , 'stripe_supported_country_type' => 'MT'],
                'Moldova' => ['code' => 'MDL', 'sign' => 'L', 'nationality' => 'Moldovan', 'country_code' => 'MD' , 'stripe_supported_country_type' => null],
                'Monaco' => ['code' => 'EUR', 'sign' => '€', 'nationality' => 'Monégasque', 'country_code' => 'MC' , 'stripe_supported_country_type' => null],
                'Montenegro' => ['code' => 'EUR', 'sign' => '€', 'nationality' => 'Montenegrin', 'country_code' => 'ME' , 'stripe_supported_country_type' => null],
                'Netherlands' => ['code' => 'EUR', 'sign' => '€', 'nationality' => 'Dutch', 'country_code' => 'NL' , 'stripe_supported_country_type' => 'NL'],
                'North Macedonia' => ['code' => 'MKD', 'sign' => 'ден', 'nationality' => 'Macedonian', 'country_code' => 'MK' , 'stripe_supported_country_type' => null],
                'Norway' => ['code' => 'NOK', 'sign' => 'kr', 'nationality' => 'Norwegian', 'country_code' => 'NO' , 'stripe_supported_country_type' => 'NO'],
                'Poland' => ['code' => 'PLN', 'sign' => 'zł', 'nationality' => 'Polish', 'country_code' => 'PL' , 'stripe_supported_country_type' => 'PL'],
                'Portugal' => ['code' => 'EUR', 'sign' => '€', 'nationality' => 'Portuguese', 'country_code' => 'PT' , 'stripe_supported_country_type' => 'PT'],
                'Romania' => ['code' => 'RON', 'sign' => 'lei', 'nationality' => 'Romanian', 'country_code' => 'RO' , 'stripe_supported_country_type' => 'RO'],
                'Russia' => ['code' => 'RUB', 'sign' => '₽', 'nationality' => 'Russian', 'country_code' => 'RU' , 'stripe_supported_country_type' => null],
                'San Marino' => ['code' => 'EUR', 'sign' => '€', 'nationality' => 'Sammarinese', 'country_code' => 'SM' , 'stripe_supported_country_type' => null],
                'Serbia' => ['code' => 'RSD', 'sign' => 'din', 'nationality' => 'Serbian', 'country_code' => 'RS' , 'stripe_supported_country_type' => null],
                'Slovakia' => ['code' => 'EUR', 'sign' => '€', 'nationality' => 'Slovak', 'country_code' => 'SK' , 'stripe_supported_country_type' => 'SK'],
                'Slovenia' => ['code' => 'EUR', 'sign' => '€', 'nationality' => 'Slovenian', 'country_code' => 'SI' , 'stripe_supported_country_type' => 'SI'] ,
                'Spain' => ['code' => 'EUR', 'sign' => '€', 'nationality' => 'Spanish', 'country_code' => 'ES' , 'stripe_supported_country_type' => 'ES'],
                'Sweden' => ['code' => 'SEK', 'sign' => 'kr', 'nationality' => 'Swedish', 'country_code' => 'SE' , 'stripe_supported_country_type' => 'SE'],
                'Switzerland' => ['code' => 'CHF', 'sign' => 'Fr', 'nationality' => 'Swiss', 'country_code' => 'CH' , 'stripe_supported_country_type' => 'CH'],
                'Turkey' => ['code' => 'TRY', 'sign' => '₺', 'nationality' => 'Turkish', 'country_code' => 'TR' , 'stripe_supported_country_type' => null],
                'Ukraine' => ['code' => 'UAH', 'sign' => '₴', 'nationality' => 'Ukrainian', 'country_code' => 'UA' , 'stripe_supported_country_type' => null],
                'United Kingdom' => ['code' => 'GBP', 'sign' => '£', 'nationality' => 'British', 'country_code' => 'GB' , 'stripe_supported_country_type' => 'GB'],
                'Vatican City' => ['code' => 'EUR', 'sign' => '€', 'nationality' => 'Vatican', 'country_code' => 'VA' ,'stripe_supported_country_type' => null],
            ],            
            'North America' => [
                'Antigua and Barbuda' => ['code' => 'XCD', 'sign' => 'EC$', 'nationality' => 'Antiguan or Barbudan', 'country_code' => 'AG' , 'stripe_supported_country_type' => null],
                'Bahamas' => ['code' => 'BSD', 'sign' => '$', 'nationality' => 'Bahamian', 'country_code' => 'BS' , 'stripe_supported_country_type' => null],
                'Barbados' => ['code' => 'BBD', 'sign' => '$', 'nationality' => 'Barbadian', 'country_code' => 'BB' , 'stripe_supported_country_type' => null],
                'Belize' => ['code' => 'BZD', 'sign' => 'BZ$', 'nationality' => 'Belizean', 'country_code' => 'BZ' , 'stripe_supported_country_type' => null],
                'Canada' => ['code' => 'CAD', 'sign' => '$', 'nationality' => 'Canadian', 'country_code' => 'CA' , 'stripe_supported_country_type' => 'CA'],
                'Costa Rica' => ['code' => 'CRC', 'sign' => '₡', 'nationality' => 'Costa Rican', 'country_code' => 'CR' , 'stripe_supported_country_type' => null],
                'Cuba' => ['code' => 'CUP', 'sign' => '$', 'nationality' => 'Cuban', 'country_code' => 'CU' , 'stripe_supported_country_type' => null],
                'Dominica' => ['code' => 'XCD', 'sign' => 'EC$', 'nationality' => 'Dominican', 'country_code' => 'DM' , 'stripe_supported_country_type' => null],
                'Dominican Republic' => ['code' => 'DOP', 'sign' => 'RD$', 'nationality' => 'Dominican', 'country_code' => 'DO' , 'stripe_supported_country_type' => null],
                'El Salvador' => ['code' => 'USD', 'sign' => '$', 'nationality' => 'Salvadoran', 'country_code' => 'SV' , 'stripe_supported_country_type' => null],
                'Grenada' => ['code' => 'XCD', 'sign' => 'EC$', 'nationality' => 'Grenadian', 'country_code' => 'GD' , 'stripe_supported_country_type' => null],
                'Guatemala' => ['code' => 'GTQ', 'sign' => 'Q', 'nationality' => 'Guatemalan', 'country_code' => 'GT' , 'stripe_supported_country_type' => null],
                'Haiti' => ['code' => 'HTG', 'sign' => 'G', 'nationality' => 'Haitian', 'country_code' => 'HT' , 'stripe_supported_country_type' => null],
                'Honduras' => ['code' => 'HNL', 'sign' => 'L', 'nationality' => 'Honduran', 'country_code' => 'HN' , 'stripe_supported_country_type' => null],
                'Jamaica' => ['code' => 'JMD', 'sign' => 'J$', 'nationality' => 'Jamaican', 'country_code' => 'JM' , 'stripe_supported_country_type' => null],
                'Mexico' => ['code' => 'MXN', 'sign' => '$', 'nationality' => 'Mexican', 'country_code' => 'MX' , 'stripe_supported_country_type' => 'MX'],
                'Nicaragua' => ['code' => 'NIO', 'sign' => 'C$', 'nationality' => 'Nicaraguan', 'country_code' => 'NI' , 'stripe_supported_country_type' => null],
                'Panama' => ['code' => 'PAB', 'sign' => 'B/.', 'nationality' => 'Panamanian', 'country_code' => 'PA' , 'stripe_supported_country_type' => null],
                'Saint Kitts and Nevis' => ['code' => 'XCD', 'sign' => 'EC$', 'nationality' => 'Kittitian or Nevisian', 'country_code' => 'KN' , 'stripe_supported_country_type' => null],
                'Saint Lucia' => ['code' => 'XCD', 'sign' => 'EC$', 'nationality' => 'Saint Lucian', 'country_code' => 'LC' , 'stripe_supported_country_type' => null],
                'Saint Vincent and the Grenadines' => ['code' => 'XCD', 'sign' => 'EC$', 'nationality' => 'Vincentian or Grenadian', 'country_code' => 'VC' , 'stripe_supported_country_type' => null],
                'Trinidad and Tobago' => ['code' => 'TTD', 'sign' => 'TT$', 'nationality' => 'Trinidadian or Tobagonian', 'country_code' => 'TT' , 'stripe_supported_country_type' => null],
                'United States' => ['code' => 'USD', 'sign' => '$', 'nationality' => 'American', 'country_code' => 'US' , 'stripe_supported_country_type' => 'US' , 'stripe_supported_country_type' => null],
            ],
            'Oceania' => [
                'Australia' => ['code' => 'AUD', 'sign' => '$', 'nationality' => 'Australian', 'country_code' => 'AU' , 'stripe_supported_country_type' => 'AU'],
                'Fiji' => ['code' => 'FJD', 'sign' => '$', 'nationality' => 'Fijian', 'country_code' => 'FJ' , 'stripe_supported_country_type' => null],
                'Kiribati' => ['code' => 'AUD', 'sign' => '$', 'nationality' => 'I-Kiribati', 'country_code' => 'KI' , 'stripe_supported_country_type' => null],
                'Marshall Islands' => ['code' => 'USD', 'sign' => '$', 'nationality' => 'Marshallese', 'country_code' => 'MH' , 'stripe_supported_country_type' => null],
                'Micronesia' => ['code' => 'USD', 'sign' => '$', 'nationality' => 'Micronesian', 'country_code' => 'FM' , 'stripe_supported_country_type' => null],
                'Nauru' => ['code' => 'AUD', 'sign' => '$', 'nationality' => 'Nauruan', 'country_code' => 'NR' , 'stripe_supported_country_type' => null],
                'New Zealand' => ['code' => 'NZD', 'sign' => '$', 'nationality' => 'New Zealander', 'country_code' => 'NZ' , 'stripe_supported_country_type' => 'NZ'],
                'Palau' => ['code' => 'USD', 'sign' => '$', 'nationality' => 'Palauan', 'country_code' => 'PW' , 'stripe_supported_country_type' => null],
                'Papua New Guinea' => ['code' => 'PGK', 'sign' => 'K', 'nationality' => 'Papua New Guinean', 'country_code' => 'PG' , 'stripe_supported_country_type' => null],
                'Samoa' => ['code' => 'WST', 'sign' => 'T', 'nationality' => 'Samoan', 'country_code' => 'WS' , 'stripe_supported_country_type' => null],
                'Solomon Islands' => ['code' => 'SBD', 'sign' => '$', 'nationality' => 'Solomon Islander', 'country_code' => 'SB' , 'stripe_supported_country_type' => null],
                'Tonga' => ['code' => 'TOP', 'sign' => 'T$', 'nationality' => 'Tongan', 'country_code' => 'TO' , 'stripe_supported_country_type' => null],
                'Tuvalu' => ['code' => 'AUD', 'sign' => '$', 'nationality' => 'Tuvaluan', 'country_code' => 'TV' , 'stripe_supported_country_type' => null],
                'Vanuatu' => ['code' => 'VUV', 'sign' => 'VT', 'nationality' => 'Ni-Vanuatu', 'country_code' => 'VU' , 'stripe_supported_country_type' => null],
            ],
            'South America' => [
                'Argentina' => ['code' => 'ARS', 'sign' => '$', 'nationality' => 'Argentine', 'country_code' => 'AR' , 'stripe_supported_country_type' => null],
                'Bolivia' => ['code' => 'BOB', 'sign' => 'Bs', 'nationality' => 'Bolivian', 'country_code' => 'BO' , 'stripe_supported_country_type' => null],
                'Brazil' => ['code' => 'BRL', 'sign' => 'R$', 'nationality' => 'Brazilian', 'country_code' => 'BR', 'stripe_supported_country_type' => 'BR'],
                'Chile' => ['code' => 'CLP', 'sign' => '$', 'nationality' => 'Chilean', 'country_code' => 'CL' , 'stripe_supported_country_type' => null],
                'Colombia' => ['code' => 'COP', 'sign' => '$', 'nationality' => 'Colombian', 'country_code' => 'CO' , 'stripe_supported_country_type' => null],
                'Ecuador' => ['code' => 'USD', 'sign' => '$', 'nationality' => 'Ecuadorian', 'country_code' => 'EC' , 'stripe_supported_country_type' => null],
                'Guyana' => ['code' => 'GYD', 'sign' => '$', 'nationality' => 'Guyanese', 'country_code' => 'GY' , 'stripe_supported_country_type' => null],
                'Paraguay' => ['code' => 'PYG', 'sign' => '₲', 'nationality' => 'Paraguayan', 'country_code' => 'PY' , 'stripe_supported_country_type' => null],
                'Peru' => ['code' => 'PEN', 'sign' => 'S/', 'nationality' => 'Peruvian', 'country_code' => 'PE' , 'stripe_supported_country_type' => null],
                'Suriname' => ['code' => 'SRD', 'sign' => '$', 'nationality' => 'Surinamese', 'country_code' => 'SR' , 'stripe_supported_country_type' => null],
                'Uruguay' => ['code' => 'UYU', 'sign' => '$', 'nationality' => 'Uruguayan', 'country_code' => 'UY' , 'stripe_supported_country_type' => null],
                'Venezuela' => ['code' => 'VES', 'sign' => 'Bs.S', 'nationality' => 'Venezuelan', 'country_code' => 'VE' , 'stripe_supported_country_type' => null],
            ],
        ];

        foreach ($countries as $continentName => $countryList) {
            $continent = Continent::where('name', $continentName)->first();

            if ($continent) {
                foreach ($countryList as $countryName => $data) {
                    Country::updateOrCreate(
                        ['name' => $countryName],  // Search criteria (Unique Identifier)
                        [
                            'currency_type' => $data['code'],
                            'currency_sign' => $data['sign'], 
                            'continent_id' => $continent->id,
                            'nationality'  => $data['nationality'],
                            'country_code' => $data['country_code'],
                            'stripe_supported_country_type'  => $data['stripe_supported_country_type']
                        ]
                    );
                }
            }
        }
    }
}
